services:
  - type: web
    name: nutricon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    disk:
      name: nutricon-db-storage
      mountPath: /data
      sizeGB: 1